services:
  postgres:
    build:
      context: .
      dockerfile: app/database/Dockerfile
    container_name: webservice_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      # expose port 8080 on the host, which is mapped to port 8080 within the container
      # (the Gunicorn application runs on port 8080 inside the container)
      - "8080:8080"
    depends_on:
      - postgres
