apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: bsznyk/webservice-template-app:latest
        ports:
          - containerPort: 8080
        env:
          - name: APP_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: app-host
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: app-port
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-db
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-port
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
