apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # base64 encoded values
  # echo -n <value-to-encode> | base64
  postgres-user: ZGJ1c2Vy
  postgres-password: ZGJwYXNz
