name: CI Pipeline

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres-test:
        image: postgres:latest
        env:
          POSTGRES_DB: webservice-db-test
          POSTGRES_USER: dbuser-test
          POSTGRES_PASSWORD: dbpass-test
        ports:
          - "7654:5432"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Run Tests
        run: pytest
